curl -X POST http://localhost:3000/api/v1/tickets \
  -H "Content-Type: application/json" \
  -d '{
    "companyId": 1,
    "type": "registrationAddressChange",
    "assigneeId": 2,
    "category": "registrationAddressChange"
  }'

###

curl -X GET http://localhost:3000/api/v1/tickets \
  -H "Content-Type: application/json"

###

curl -X GET http://localhost:3000/api/v1/tickets/status/5 \
  -H "Content-Type: application/json"